# OS Init Arch generated tmux config

unbind-key C-b
set-option -g prefix C-h
bind-key C-b send-prefix
bind-key r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"

unbind-key '"'
unbind-key %
bind-key - split-window -v -c "#{pane_current_path}"
bind-key | split-window -h -c "#{pane_current_path}"

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

set-option -g default-terminal "screen-256color"
set-option -g base-index 1
set-option -g pane-base-index 1
set-option -g renumber-windows on
set-option -g history-limit 500000
set-window-option -g mode-keys vi
