# OS-INIT -- file descriptor and process limits
* hard nofile 1048576
* soft nofile 1048576
root hard nofile 1048576
root soft nofile 1048576

* soft nproc 65535
* hard nproc 65535
root soft nproc 65535
root hard nproc 65535

* hard stack 131072
* soft stack 131072
