# OS-INIT -- file descriptor and process limits, adapted from dpanic/patchfiles
* hard nofile 2097152
* soft nofile 2097152
root hard nofile 2097152
root soft nofile 2097152

* soft nproc 65535
* hard nproc 65535
root soft nproc 65535
root hard nproc 65535

* hard stack 131072
* soft stack 131072
